name: energy-trading
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - statsmodels
  - scipy
  - scikit-learn
  - yfinance
  - jupyter
  - ipykernel
  - pip
  - pip:
      - pmdarima
      - plotly
      - yfinance
